hero_policy_file: hero_policy_state.pth
hero_target_file: hero_target_state.pth
gun_policy_file: gun_policy_state.pth
gun_target_file: gun_target_state.pth
hero_optim_file: hero_optimizer.pth
gun_optim_file: gun_optimizer.pth
hero_policy_class: theseus.models.GraphDQN.ActionGNN.HeroGNN
gun_policy_class: theseus.models.GraphDQN.ActionGNN.GunGNN
epsilon: 0.7787764418703357
sync_steps_taken: 122
learning_rate: 0.0001
discount_factor: 0.99
mini_batch_size: 64
target_sync_rate: 500
epsilon_decay: 0.99975
epsilon_min: 0.05
log_window_size: 100
save_interval: 500
replay_memory_size: 63793
total_reward_hero: 15519.5
total_reward_gun: 1812.0
loss_fn_class: torch.nn.modules.loss.MSELoss
optimizer_class: torch.optim.adamw.AdamW
